// !!! This is a file automatically generated by hipify!!!
/*
 * SPDX-FileCopyrightText: Copyright (c) 2023-2026 NVIDIA CORPORATION & AFFILIATES. All rights reserved.
 * SPDX-License-Identifier: Apache-2.0
 */
#pragma once
#include <torch/extension.h>
#include <string>
#include <hip/hip_runtime.h>
#include <hip/hip_runtime.h>
#include <c10/hip/HIPStream.h>


namespace curobo{
    namespace common{
        inline void validate_cuda_input(const torch::Tensor& x, const std::string& name){
            AT_ASSERTM(x.is_cuda(),  name + " must be a CUDA tensor");
            AT_ASSERTM(x.is_contiguous(),  name + " must be contiguous");
        }
        inline hipStream_t get_cuda_stream(){
            return at::cuda::getCurrentCUDAStream();
        }
        inline hipStream_t get_current_cuda_stream(){
            return at::cuda::getCurrentCUDAStream();
        }
    }
}